tugas2 fany
aldhi88/program2sem4pagib pull request #29
Opened 2023-05-21 08:41 UTC by FanyFadhilah

tugas fany

2023-05-24 03:27 UTC, FanyFadhilah commented
@aldhi88 ini pak tugasnya 
![IMG-20230524-WA0000](https://github.com/aldhi88/program2sem4pagib/assets/129471406/01698d10-16ba-4dbc-8f5a-cdf4d65b1ca3)

2023-05-25 06:01 UTC, aldhi88 requested changes
@FanyFadhilah , branch kamu masih salah, perbaiki semua yg saya revisi ya, perhatikan instruksi dengan baik ya

2023-05-25 06:01 UTC, aldhi88 commented on tugas2/2155201053/proses.php
@FanyFadhilah , ini kenapa code nya seperti ini? harus nya error ni code kamu

2023-05-25 06:01 UTC, aldhi88 commented on tugas2/2155201053/form fany.php
@FanyFadhilah , ini file untuk apa? yg gak perlu di hapus

2023-06-23 01:50 UTC, closed without merging